name: Full CI Pipeline

on:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3

  sca:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3

  sast:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

  test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3

  build-and-push:
    needs: [lint, sca, sast, test]
    runs-on: self-hosted
   
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/react-app:latest .
      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/react-app:latest
