name: Full CI Pipeline

on:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3

  sca:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3

  sast:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

  test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3

  build-and-push:
    needs: [lint, sca, sast, test]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/react-app:latest .
      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/react-app:latest

  deploy-to-kubernetes:
    needs: [build-and-push]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f react-app/k8s/deployment.yaml
          kubectl apply -f react-app/k8s/service.yaml
          kubectl rollout status deployment/react-app

  dast:
    if: false  # 👈 Passive DAST is disabled by default
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP ZAP Passive Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'http://your-app-url.com'  # Replace with your actual app URL
          rules_file_name: ''
          allow_issue_writing: false
          
